# use Cypress provided image with all dependencies included
FROM cypress/base:12
RUN node --version
RUN npm --version

# Install OpenJDK-8
RUN apt-get update && \
  apt-get install -y openjdk-8-jdk && \
  apt-get install -y ant && \
  apt-get clean;

RUN apt-get update && \
  apt-get install ca-certificates-java && \
  apt-get clean && \
  update-ca-certificates -f;

ENV JAVA_HOME /usr/lib/jvm/java-8-openjdk-amd64/
RUN export JAVA_HOME
RUN java -version

WORKDIR /home/node/app

ENV CI=1
ENV HOME=/tmp